#!/bin/sh

xrdb $HOME/.Xresources
xsetroot -solid grey
x-terminal-emulator -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &
#x-window-manager &
# Fix to make GNOME work
export XKL_XMODMAP_DISABLE=1
xhost +
(sleep 5 && sudo -u test /apps/squashfs-root/qgroundcontrol-start.sh ) &
(sleep 7 && wmctrl -ir $(wmctrl -l | grep QGroundControl | cut -d ' ' -f 1) -b add,maximized_vert,maximized_horz) &
#/etc/X11/Xsession
startlxde &
python3 /usr/local/bin/autostart_mission.py